### ISSUE TITLE
followers_list_new

### ISSUE THREAD

**Issue by edinsof** [cabhijith/InstagramBot-#1]
Hi
im testing you code
Where is (followers_list_new) file ?

**Comment by cabhijith** [comment]
Hey!
Sorry for the late reply, missed the issue!
The followers_list_new file should be added to the folder in which you run bot.py on!
Do let me know if you want any further help!

**Comment by edinsof** [comment]
hi what is the extension or file type for (followers_list_new) ?
i cant get to work it on windows 10 because file (followers_list_new) is missing :(

you can share (followers_list_new) example  file?

**Comment by cabhijith** [comment]
Hi!
followers_list_new will be a Python Pickle file (.pkl). It's somewhat similar to JSON but only for Python.  
Oh! Good catch. The first time you run, you have to create the new .pkl file. I'll add that to Bot.py. Here is how you do it:

```
filename = 'followers_list_new'
outfile = open(filename,'wb')
```
Once you have made the file, remove the code in the subsequent runs. Do let me know if there are any other issues:)

PS: If it still doesn't work, please post the error and I'll help you out!

**Comment by edinsof** [comment]
Hi
file is created but now i get this error
`Traceback (most recent call last):
  File "Bot.py", line 29, in <module>
    followers_list= pickle.load(f)
EOFError: Ran out of input`

it's because followers_list_new is empty ?

**Comment by cabhijith** [comment]
Hey!
Yes.  I have added a`followers_list_neww` file, so anyone using it for the next time won't have any problem! Try `git pull` again and it should work. Do let me know if there are any error(s)

**Comment by edinsof** [comment]
Hi
bot now is working fine after comment line 39
`start_time = time.time()`

thank you :)

**Comment by cabhijith** [comment]
Great! Yup, that line proves to be troublesome, sometimes. I am closing this issue. If there is something unresolved, please start a new one. Cheers!
